# Generated by Django 5.0.1 on 2025-10-16 07:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('action_type', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Journal d'audit coordinateur",
                'verbose_name_plural': "Journaux d'audit coordinateur",
                'db_table': 'coordinateur_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DecashmentValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('purchase', 'Achat'), ('payment', 'Paiement'), ('decashment', 'Décaissement'), ('stock_transfer', 'Transfert de stock')], max_length=50)),
                ('request_id', models.UUIDField()),
                ('validation_status', models.CharField(choices=[('en_attente', 'En attente'), ('validé', 'Validé'), ('rejeté', 'Rejeté')], default='en_attente', max_length=20)),
                ('validated_by', models.UUIDField(blank=True, null=True)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('requested_by', models.UUIDField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Validation de décaissement',
                'verbose_name_plural': 'Validations de décaissement',
                'db_table': 'decashment_validations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_by', models.UUIDField()),
                ('operation_type', models.CharField(max_length=100)),
                ('operation_id', models.UUIDField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Consultation d'opération",
                'verbose_name_plural': "Consultations d'opérations",
                'db_table': 'operation_views',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
