services:

  # ============================
  # KONG (API GATEWAY)
  # ============================
  kong:
    image: kong:3.4
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_SSL_CERT: /etc/kong/ssl/cert.pem
      KONG_SSL_CERT_KEY: /etc/kong/ssl/key.pem
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: notice
      KONG_PLUGINS: bundled,correlation-id
      KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE: 100m
      KONG_REAL_IP_HEADER: X-Forwarded-For
      KONG_TRUSTED_IPS: 0.0.0.0/0,::/0
    volumes:
      - ./kong/ssl:/etc/kong/ssl
      - ./kong/kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"   # au lieu de "80:8000"
      - "8443:8000"     # HTTPS
      - "127.0.0.1:8001:8001"  # Admin API, accessible uniquement localement
    depends_on:
      - auth_service
      - rh_service
      - stock_service
      - finance_service
      - cordo_service
    networks:
      - project_network

  # ============================
  # AUTH SERVICE
  # ============================
  auth_service:
    build: ./auth_service
    container_name: auth_service
    env_file: ./auth_service/.env
    ports:
      - "8000"   # accessible uniquement depuis le réseau interne
    restart: unless-stopped
    networks:
      - project_network

  # ============================
  # RH SERVICE
  # ============================
  rh_service:
    build: ./rh_service
    container_name: rh_service
    env_file: ./rh_service/.env
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - project_network

  # ============================
  # STOCK SERVICE
  # ============================
  stock_service:
    build: ./stock_service
    container_name: stock_service
    env_file: ./stock_service/.env
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - project_network

  # ============================
  # FINANCE SERVICE
  # ============================
  finance_service:
    build: ./finance_service
    container_name: finance_service
    env_file: ./finance_service/.env
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - project_network

  # ============================
  # CORDO SERVICE
  # ============================
  cordo_service:
    build: ./cordo_service
    container_name: cordo_service
    env_file: ./cordo_service/.env
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - project_network

# ============================
# NETWORK
# ============================
networks:
  project_network:
    driver: bridge
