# Generated by Django 4.2.26 on 2025-11-13 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unite_mesure', models.CharField(default='unité', max_length=50)),
                ('prix_unitaire_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('type_categorie', models.CharField(choices=[('matiere_premiere', 'Matière première'), ('produit_fini', 'Produit fini'), ('consommable', 'Consommable')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_inventaire', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable_id', models.UUIDField(help_text="UUID du magasinier qui réalise l'inventaire")),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_cours', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('valideur_id', models.UUIDField(blank=True, help_text="UUID du responsable stock qui valide l'inventaire", null=True)),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'db_table': 'inventaires',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('district_id', models.UUIDField(help_text='ID du district (depuis service RH)')),
                ('capacite_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'db_table': 'magasins',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('responsable_id', models.UUIDField(help_text='UUID du responsable stock qui crée le transfert')),
                ('date_transfert', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('recu', 'Reçu')], default='en_attente', max_length=20)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to='stock.article')),
                ('magasin_dest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entree', to='stock.magasin')),
                ('magasin_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortie', to='stock.magasin')),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'db_table': 'transferts_stock',
                'ordering': ['-date_transfert'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('retour', 'Retour'), ('transfert', 'Transfert'), ('inventaire', 'Inventaire')], max_length=20)),
                ('magasinier_id', models.UUIDField(help_text='ID du magasinier (depuis auth_service)')),
                ('recepteur_id', models.UUIDField(blank=True, help_text='ID du recepteur (employé ou magasin)', null=True)),
                ('recepteur_type', models.CharField(choices=[('employe', 'Employé (depuis RH)'), ('magasin', 'Magasin'), ('autre', 'Autre')], default='magasin', max_length=50)),
                ('transporteur', models.CharField(blank=True, max_length=255, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.article')),
                ('magasin_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_entree', to='stock.magasin')),
                ('magasin_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_sortie', to='stock.magasin')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'mouvements_stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_comptée', models.IntegerField()),
                ('quantite_stock', models.IntegerField(default=0)),
                ('ecart', models.IntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventaire')),
            ],
        ),
        migrations.AddField(
            model_name='inventaire',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='stock.magasin'),
        ),
        migrations.CreateModel(
            name='DemandeReapprovisionnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('quantite_demandee', models.IntegerField()),
                ('quantite_approuvee', models.IntegerField(blank=True, null=True)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('demandeur_id', models.UUIDField(help_text='UUID du magasinier connecté')),
                ('validateur_id', models.UUIDField(blank=True, help_text='UUID du responsable stock', null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_reappro', to='stock.article')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_reappro', to='stock.magasin')),
            ],
            options={
                'verbose_name': 'Demande de réapprovisionnement',
                'verbose_name_plural': 'Demandes de réapprovisionnement',
                'db_table': 'demandes_reapprovisionnement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('quantite', models.IntegerField()),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('demandeur_id', models.UUIDField(help_text='UUID du magasinier connecté')),
                ('finance_valideur_id', models.UUIDField(blank=True, help_text='UUID du responsable finance', null=True)),
                ('justification', models.TextField()),
                ('date_validation_finance', models.DateTimeField(blank=True, null=True)),
                ('commentaire_finance', models.TextField(blank=True)),
                ('statut_reception', models.CharField(choices=[('en_attente', 'En attente'), ('recu', 'Reçu')], default='en_attente', max_length=20)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('magasin_reception_id', models.UUIDField(blank=True, help_text="Magasin qui reçoit l'achat", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_achat', to='stock.article')),
            ],
            options={
                'verbose_name': "Demande d'achat",
                'verbose_name_plural': "Demandes d'achat",
                'db_table': 'demandes_achat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='stock.categorie'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=10)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.article')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.magasin')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stocks',
                'ordering': ['article', 'magasin'],
                'unique_together': {('article', 'magasin')},
            },
        ),
    ]
