server {
    listen 80;
    server_name api.ecartmada.com;

    location /media/ {
        alias /app/media/;
        access_log off;
        expires 30d;
        add_header Access-Control-Allow-Origin *;
    }
}
