# Generated by Django 5.2.8 on 2025-11-10 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_fonction', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'ordering': ['nom_fonction'],
            },
        ),
        migrations.CreateModel(
            name='ModePayement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode_payement', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode de Paiement',
                'verbose_name_plural': 'Modes de Paiement',
                'ordering': ['mode_payement'],
            },
        ),
        migrations.CreateModel(
            name='TypeAchat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_achat', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Type d'Achat",
                'verbose_name_plural': "Types d'Achats",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_contrat', models.CharField(max_length=50, unique=True)),
                ('nom_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Contrat',
                'verbose_name_plural': 'Types de Contrats',
                'ordering': ['nom_type'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='rh.district')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['district', 'name'],
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_employer', models.CharField(max_length=100)),
                ('prenom_employer', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('status_employer', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'En congé'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('date_entree', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profil/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv_employes/')),
                ('diplome', models.CharField(blank=True, choices=[('bacc', 'BACC'), ('bacc+2', 'BACC + 2'), ('licence', 'Licence'), ('master', 'Master')], max_length=20, null=True)),
                ('domaine_etude', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='rh.district')),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='rh.fonction')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom_employer', 'prenom_employer'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('en_cours', 'En cours')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='rh.employer')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_conge', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_creation_conge', models.DateTimeField(auto_now_add=True)),
                ('date_fin_conge', models.DateField()),
                ('date_debut_conge', models.DateField()),
                ('motif_conge', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='rh.employer')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_creation_conge'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_affectation', models.CharField(choices=[('permanente', 'Permanente'), ('temporaire', 'Temporaire'), ('mission', 'Mission')], default='permanente', max_length=20)),
                ('status_affectation', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée')], default='active', max_length=20)),
                ('date_creation_affectation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ancien_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciennes_affectations', to='rh.district')),
                ('nouveau_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nouvelles_affectations', to='rh.district')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='rh.employer')),
                ('ancienne_fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciennes_affectations', to='rh.fonction')),
                ('nouveau_fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nouvelles_affectations', to='rh.fonction')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-date_creation_affectation'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='rh.affectation')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['ville'],
            },
        ),
        migrations.CreateModel(
            name='Electricite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_compteur', models.CharField(max_length=50, unique=True)),
                ('fournisseur', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricites', to='rh.location')),
            ],
            options={
                'verbose_name': 'Électricité',
                'verbose_name_plural': 'Électricités',
            },
        ),
        migrations.CreateModel(
            name='Loyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_echeance', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyers', to='rh.location')),
            ],
            options={
                'verbose_name': 'Loyer',
                'verbose_name_plural': 'Loyers',
                'ordering': ['-date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_payement', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complété'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payements', to='rh.demande')),
                ('electricite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payements', to='rh.electricite')),
                ('loyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payements', to='rh.loyer')),
                ('mode_payement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payements', to='rh.modepayement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_payement'],
            },
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=200)),
                ('code_achat', models.CharField(max_length=50, unique=True)),
                ('nombre', models.IntegerField(default=1)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_achat', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_achat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='rh.typeachat')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_contrat', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('date_debut_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='rh.employer')),
                ('type_contrat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='rh.typecontrat')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut_contrat'],
            },
        ),
        migrations.CreateModel(
            name='Fokontany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fokontanies', to='rh.commune')),
            ],
            options={
                'verbose_name': 'Fokontany',
                'verbose_name_plural': 'Fokontanies',
                'ordering': ['commune', 'name'],
                'unique_together': {('name', 'commune')},
            },
        ),
    ]
