# Generated by Django 5.2.8 on 2025-11-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
    ]
