# Generated by Django 5.2.8 on 2025-11-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_add_employer_to_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
