# Generated by Django 5.2.8 on 2025-11-10 15:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_affectation_remarque'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nombre_jours_max', models.IntegerField(help_text='Nombre maximum de jours autorisés pour ce type de congé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Congé',
                'verbose_name_plural': 'Types de Congés',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='conge',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Congé', 'verbose_name_plural': 'Congés'},
        ),
        migrations.RemoveField(
            model_name='conge',
            name='date_creation_conge',
        ),
        migrations.RemoveField(
            model_name='conge',
            name='date_debut_conge',
        ),
        migrations.RemoveField(
            model_name='conge',
            name='date_fin_conge',
        ),
        migrations.RemoveField(
            model_name='conge',
            name='motif_conge',
        ),
        migrations.AddField(
            model_name='conge',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conge',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conge',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conge',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs_conge/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='conge',
            name='motif',
            field=models.TextField(default='Non précisé'),
        ),
        migrations.AddField(
            model_name='conge',
            name='nombre_jours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conge',
            name='type_conge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges', to='rh.typeconge'),
        ),
    ]
