# Generated by Django 5.2.8 on 2025-11-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_typeconge_alter_conge_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conge',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conge',
            name='motif',
            field=models.TextField(),
        ),
    ]
