# Generated by Django 5.2.8 on 2025-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_alter_conge_date_creation_alter_conge_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='status_conge',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
    ]
