# Generated by Django 5.2.8 on 2025-11-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_alter_conge_status_conge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecontrat',
            name='type_contrat',
        ),
    ]
