# Generated by Django 5.2.8 on 2025-11-11 08:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_remove_typecontrat_type_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payement',
            name='loyer',
        ),
        migrations.AlterModelOptions(
            name='achat',
            options={'ordering': ['article'], 'verbose_name': 'Achat', 'verbose_name_plural': 'Achats'},
        ),
        migrations.AlterModelOptions(
            name='demande',
            options={'ordering': ['-date_demande']},
        ),
        migrations.AlterModelOptions(
            name='electricite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modepayement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payement',
            options={'ordering': ['-date_payement']},
        ),
        migrations.RemoveField(
            model_name='achat',
            name='date_achat',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='location',
            name='affectation',
        ),
        migrations.RemoveField(
            model_name='payement',
            name='demande',
        ),
        migrations.AddField(
            model_name='achat',
            name='demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='rh.demande'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='description_mission',
            field=models.TextField(blank=True, help_text='Détails de la mission ou de la prestation', null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='duree_jours',
            field=models.PositiveIntegerField(blank=True, help_text='Durée effective du contrat en jours', null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total à payer (utile pour une mission ou prestation)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='nature_contrat',
            field=models.CharField(choices=[('emploi', 'Contrat de travail'), ('prestation', 'Contrat de prestation'), ('mission', 'Contrat de mission')], default='emploi', help_text='Définit si c’est un contrat de travail, de mission ou de prestation', max_length=20),
        ),
        migrations.AddField(
            model_name='demande',
            name='payements',
            field=models.ManyToManyField(blank=True, related_name='demandes', to='rh.payement'),
        ),
        migrations.AddField(
            model_name='electricite',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='location',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='location',
            name='nom',
            field=models.CharField(default='Nom par défaut', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='type_location',
            field=models.CharField(default='inconnu', max_length=50),
        ),
        migrations.AddField(
            model_name='payement',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payements', to='rh.contrat'),
        ),
        migrations.AddField(
            model_name='payement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payements', to='rh.location'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='status_contrat',
            field=models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié'), ('suspendu', 'Suspendu'), ('termine', 'Terminé')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payement',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Loyer',
        ),
    ]
