# Generated by Django 4.2.7 on 2025-10-16 07:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('action_type', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Journal d'audit Finance",
                'verbose_name_plural': "Journaux d'audit Finance",
                'db_table': 'finance_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DecashmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by', models.UUIDField()),
                ('source_service', models.CharField(choices=[('rh', 'RH'), ('stock', 'Stock'), ('finance', 'Finance')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('related_request_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_request_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('processing', 'En traitement'), ('completed', 'Complété')], default='pending', max_length=50)),
                ('validated_by', models.UUIDField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de décaissement',
                'verbose_name_plural': 'Demandes de décaissement',
                'db_table': 'decashment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('bulletin_paie', 'Bulletin de paie'), ('facture', 'Facture'), ('bon_entree', "Bon d'entrée"), ('bon_sortie', 'Bon de sortie'), ('recu_paiement', 'Reçu de paiement'), ('ordre_virement', 'Ordre de virement'), ('autre', 'Autre')], max_length=50)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('related_entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('uploaded_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_type', models.CharField(choices=[('achat_stock', 'Achat Stock'), ('salaire', 'Salaire'), ('prime', 'Prime'), ('indemnite', 'Indemnité'), ('loyer', 'Loyer'), ('carburant', 'Carburant'), ('transport', 'Transport'), ('fourniture', 'Fourniture'), ('maintenance', 'Maintenance'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('related_request_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('paid', 'Payé')], default='pending', max_length=50)),
                ('requested_by', models.UUIDField()),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('executed_by', models.UUIDField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('decashment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.decashmentrequest')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.document')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'db_table': 'expenses',
                'ordering': ['-date_requested'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField()),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('related_entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('mobile_money', 'Mobile Money')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_account', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=50)),
                ('executed_by', models.UUIDField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='finance.expense')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'payments',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('rh', 'RH'), ('stock', 'Stock'), ('finance', 'Finance'), ('general', 'Général')], max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiscal_year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'budgets',
                'ordering': ['-fiscal_year', '-month'],
                'unique_together': {('department', 'category', 'fiscal_year', 'month')},
            },
        ),
    ]
