# Generated by Django 4.2.7 on 2025-11-13 16:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDecaissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=100, unique=True)),
                ('demandeur_finance_id', models.UUIDField(help_text='UUID du responsable finance (depuis auth_service)')),
                ('validateur_coordinateur_id', models.UUIDField(blank=True, help_text='UUID du coordinateur qui valide (depuis auth_service)', null=True)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=15)),
                ('justification', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('demande_rh_id', models.UUIDField(blank=True, help_text='UUID de la demande RH (contrat, congé, etc.)', null=True)),
                ('demande_stock_id', models.UUIDField(blank=True, help_text="UUID de la demande d'achat (depuis stock_service)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de Décaissement',
                'verbose_name_plural': 'Demandes de Décaissement',
                'db_table': 'demandes_decaissement',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='TypeDecaissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_decaissement', models.CharField(choices=[('salaire', 'Salaire'), ('achat', 'Achat'), ('location', 'Location'), ('electricite', 'Électricité'), ('mission', 'Mission'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Décaissement',
                'verbose_name_plural': 'Types de Décaissement',
                'db_table': 'types_decaissement',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ValidationDemande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=100, unique=True)),
                ('type_demande', models.CharField(choices=[('contrat', 'Contrat'), ('achat_stock', 'Achat Stock'), ('location', 'Location'), ('electricite', 'Électricité')], max_length=50)),
                ('demande_origine_id', models.UUIDField(help_text="UUID de la demande d'origine (RH ou Stock)")),
                ('service_origine', models.CharField(choices=[('rh_service', 'RH'), ('stock_service', 'Stock')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('validateur_finance_id', models.UUIDField(blank=True, help_text='UUID du responsable finance (depuis auth_service)', null=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Validation de Demande RH/Stock',
                'verbose_name_plural': 'Validations de Demandes RH/Stock',
                'db_table': 'validations_demandes',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('employer_id', models.UUIDField(blank=True, help_text="UUID de l'employé (depuis rh_service)", null=True)),
                ('demande_rh_id', models.UUIDField(blank=True, help_text='UUID de la demande RH (depuis rh_service)', null=True)),
                ('demande_stock_id', models.UUIDField(blank=True, help_text="UUID de la demande d'achat (depuis stock_service)", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('responsable_finance_id', models.UUIDField(help_text='UUID du responsable finance (depuis auth_service)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande_decaissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='finance.demandedecaissement')),
                ('type_depense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='finance.typedecaissement')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'db_table': 'depenses',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='demandedecaissement',
            name='type_decaissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_decaissement', to='finance.typedecaissement'),
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=100, unique=True)),
                ('employer_id', models.UUIDField(help_text="UUID de l'employé (depuis rh_service)")),
                ('mois', models.IntegerField(help_text='Mois du paiement (1-12)')),
                ('annee', models.IntegerField(help_text='Année du paiement')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('primes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retenues', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('envoye', 'Envoyé')], default='brouillon', max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('responsable_finance_id', models.UUIDField(help_text='UUID du responsable finance (depuis auth_service)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins_paie', to='finance.depense')),
            ],
            options={
                'verbose_name': 'Bulletin de Paie',
                'verbose_name_plural': 'Bulletins de Paie',
                'db_table': 'bulletins_paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employer_id', 'mois', 'annee')},
            },
        ),
    ]
