server {
    listen 80;
    server_name api.ecartmada.com;

    # -------------------------
    # Servir les fichiers médias
    # -------------------------
    location /media/ {
        alias /app/media/;   # correspond au volume monté depuis rh_service
        autoindex off;
        access_log off;
        expires 30d;         # mise en cache côté navigateur
    }

    # -------------------------
    # Proxy vers le service RH
    # -------------------------
    location / {
        proxy_pass http://rh_service:8000;  # ton service Django
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
