server {
    listen 80;
    server_name api.ecartmada.com;

    # Servir les fichiers médias
    location /media/ {
        alias /app/media/;  # Chemin vers ton dossier media dans le container Django
    }

    # Passer le reste vers Django via Kong ou directement
    location / {
        proxy_pass http://rh_service:8000;  # ton service Django
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
