# Generated by Django 4.2.7 on 2025-11-13 16:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vue_DemandesPendantes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('dossier_numero', models.CharField(max_length=100)),
                ('demande_numero', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type_decaissement', models.CharField(max_length=100)),
                ('coordinateur_nom', models.CharField(max_length=255)),
                ('demandeur_finance_id', models.UUIDField()),
                ('date_reception', models.DateTimeField()),
                ('date_limite', models.DateTimeField()),
                ('priorite', models.CharField(max_length=20)),
                ('jours_restants', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vue Demandes Pendantes',
                'verbose_name_plural': 'Vue Demandes Pendantes',
                'db_table': 'vue_demandes_pendantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DossierDecaissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=100, unique=True)),
                ('demande_decaissement_id', models.UUIDField(help_text='UUID de la DemandeDecaissement (depuis finance_service)')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('type_decaissement', models.CharField(help_text='Type du décaissement', max_length=100)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=15)),
                ('justification', models.TextField()),
                ('demandeur_finance_id', models.UUIDField(help_text='UUID du responsable finance (depuis auth_service)')),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('date_limite_decision', models.DateTimeField(help_text='Date limite pour décider (généralement 3-5 jours)')),
                ('notes_interne', models.TextField(blank=True, help_text='Notes internes du coordinateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dossier de Décaissement',
                'verbose_name_plural': 'Dossiers de Décaissement',
                'db_table': 'dossiers_decaissement',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='ModeleDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('montant_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('type_decaissement', models.CharField(blank=True, help_text='Type de décaissement concerné (vide = tous)', max_length=100)),
                ('decision_defaut', models.CharField(choices=[('approuve', 'Approuvé'), ('rejete', 'Rejeté')], help_text='Décision suggérée', max_length=20)),
                ('commentaire_template', models.TextField(blank=True, help_text='Template de commentaire')),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de Décision',
                'verbose_name_plural': 'Modèles de Décisions',
                'db_table': 'modeles_decisions',
            },
        ),
        migrations.CreateModel(
            name='ProfilCoordinateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text="UUID de l'utilisateur (depuis auth_service)", unique=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('peut_valider_decaissement', models.BooleanField(default=True)),
                ('peut_valider_demandes_rh', models.BooleanField(default=False)),
                ('peut_valider_demandes_stock', models.BooleanField(default=False)),
                ('date_embauche', models.DateField()),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Coordinateur',
                'verbose_name_plural': 'Profils Coordinateurs',
                'db_table': 'profils_coordinateurs',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('en_attente', 'En attente'), ('renvoi', 'Renvoi pour modifications')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('montant_approuve', models.DecimalField(blank=True, decimal_places=2, help_text='Montant approuvé (peut être différent de la demande)', max_digits=15, null=True)),
                ('raison_rejet', models.TextField(blank=True, help_text='Raison du rejet si applicable')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('pieces_justificatives', models.JSONField(default=list, help_text='Liste des UUIDs de fichiers joints')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations_effectuees', to='cordo.profilcoordinateur')),
                ('dossier_decaissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_validations', to='cordo.dossierdecaissement')),
            ],
            options={
                'verbose_name': 'Historique de Validation',
                'verbose_name_plural': 'Historiques de Validations',
                'db_table': 'historiques_validations',
                'ordering': ['-date_validation'],
            },
        ),
        migrations.AddField(
            model_name='dossierdecaissement',
            name='coordinateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_decaissement', to='cordo.profilcoordinateur'),
        ),
        migrations.CreateModel(
            name='AlerteDecaissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_alerte', models.CharField(choices=[('date_limite', 'Date limite approchante'), ('montant_eleve', 'Montant élevé'), ('type_suspect', 'Type de décaissement suspect'), ('coordinateur_indisponible', 'Coordinateur indisponible')], max_length=50)),
                ('severite', models.CharField(choices=[('info', 'Information'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lue_le', models.DateTimeField(blank=True, null=True)),
                ('dossier_decaissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='cordo.dossierdecaissement')),
            ],
            options={
                'verbose_name': 'Alerte de Décaissement',
                'verbose_name_plural': 'Alertes de Décaissements',
                'db_table': 'alertes_decaissements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatistiquesValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mois', models.IntegerField(help_text='Mois (1-12)')),
                ('annee', models.IntegerField(help_text='Année')),
                ('total_demandes_traitees', models.IntegerField(default=0)),
                ('demandes_approuvees', models.IntegerField(default=0)),
                ('demandes_rejetees', models.IntegerField(default=0)),
                ('demandes_renvoyees', models.IntegerField(default=0)),
                ('montant_total_demande', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_total_approuve', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_total_rejete', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('temps_moyen_traitement', models.FloatField(default=0)),
                ('taux_approbation', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='cordo.profilcoordinateur')),
            ],
            options={
                'verbose_name': 'Statistiques de Validation',
                'verbose_name_plural': 'Statistiques de Validations',
                'db_table': 'statistiques_validations',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('coordinateur', 'mois', 'annee')},
            },
        ),
        migrations.AddIndex(
            model_name='dossierdecaissement',
            index=models.Index(fields=['coordinateur', '-date_reception'], name='dossiers_de_coordin_6b40cc_idx'),
        ),
        migrations.AddIndex(
            model_name='dossierdecaissement',
            index=models.Index(fields=['demande_decaissement_id'], name='dossiers_de_demande_ab0216_idx'),
        ),
    ]
