# Generated by Django 5.2.8 on 2025-11-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_id',
            field=models.UUIDField(blank=True, help_text='Magasin assigné au magasinier', null=True, unique=True),
        ),
    ]
