# Generated by Django 5.2.8 on 2025-11-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_id',
        ),
        migrations.AddField(
            model_name='user',
            name='magasin_id',
            field=models.UUIDField(blank=True, help_text='Magasin assigné au magasinier', null=True, unique=True),
        ),
    ]
