# Generated by Django 5.2.8 on 2025-11-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_store_id_user_magasin_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='magasin_id',
            field=models.UUIDField(blank=True, help_text='Identifiant du magasin associé (UUID)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable_rh', 'Responsable RH'), ('responsable_stock', 'Responsable Stock'), ('responsable_finance', 'Responsable Finance'), ('magasinier', 'Magasinier'), ('coordinateur', 'Coordinateur')], default='coordinateur', max_length=50),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
