# Generated by Django 5.2.8 on 2025-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_notification_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, help_text='Identifiant ou référence de l’entité (UUID ou URL)', max_length=255, null=True),
        ),
    ]
